- hosts: 172.18.85.134
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      definition: 'service.yml'
      validate_certs: no
      namespace: default
  - name: Deploy the application
    k8s:
      state: present
      validate_certs: no
      namespace: default
      definition: 'deployment.yml'
